[build]
  publish = "out"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  # Enable PostgreSQL native bindings
  PYTHON_VERSION = "3.8"

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers for security and CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Redirects
[[redirects]]
  from = "/dashboard"
  to = "/admin"
  status = 301

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth-nextauth"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (set these in Netlify dashboard)
# Required for all deployments:
# NEXTAUTH_URL
# NEXTAUTH_SECRET  
# ADMIN_EMAIL
# ADMIN_PASSWORD

# For PostgreSQL/Neon DB (recommended):
# NEON_DATABASE_URL
# NEON_MAX_CONNECTIONS
# NEON_IDLE_TIMEOUT
# NEON_CONNECTION_TIMEOUT

# For SQLite (legacy):
# DATABASE_PATH

# Optional performance settings:
# ENABLE_PERFORMANCE_MONITORING
# SLOW_QUERY_THRESHOLD
# NEON_REGION

# Build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Edge functions (optional, for advanced routing)
# [[edge_functions]]
#   function = "auth"
#   path = "/admin/*"